name: Code Review

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  lint-and-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    #run lint
    - name: Run lint
      run: npm run lint

    - name: Static Code Analysis
      run: npm run analyze

      - name: Analyze code quality metrics
        # run: npm run analyze
        run: echo "Analyzing code quality metrics"

      - name: Scan for security vulnerabilities
        # run: npm audit
        run: echo "Scanning for security vulnerabilities"

      - name: Send code review feedback
        run: |
          chmod +x ./scripts/review_feedback.sh
          ./scripts/review_feedback.sh
