name: Generate Release Notes

on:
  pull_request:
    branches:
      - main

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate Release Notes
        # id: generate_notes
        # uses: decathlon/release-notes-generator-action@v1.4.4
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   configuration-path: '.github/release-notes-config.yml'
        run : echo "Generating release notes"

      - name: Create Release
        # uses: actions/create-release@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tag_name: ${{ github.ref }}
        #   release_name: Release ${{ github.ref }}
        #   body: ${{ steps.generate_notes.outputs.release_notes }}
        #   draft: false
        #   prerelease: false
        run: echo "Creating release"

      - name: Cleanup Post-Release
        run: echo "Additional cleanup tasks can be added here."


      - name: Authenticate Snyk and run security scan
        # run: npx snyk auth ${{ secrets.ASSIGNMENT_TOKEN }} # Provide your Snyk token here
        # run: npx snyk test
        run: echo "Authenticating Snyk and running security scan"

      - name: Custom workflow commpleted
        run: echo "Custom workflow completed"
