name: Deployment to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'  # Fetch the gh-pages branch

      - name: Fetch changes
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/gh-pages:refs/remotes/origin/gh-pages

      - name: Reset branch
        run: git reset --hard origin/gh-pages

      - uses: actions/checkout@v2
        with:
          ref: 'main'  # Switch back to main branch

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # - name: Build
      #   run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
