name: Scheduled Maintenance

on:
  schedule:
    #runs 5 pm every day
    -cron: '0 17 * * *'
    # - cron: '0 2 * * *' # Runs at 2 AM every day

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run backup script
      run: ./scripts/backup.sh
    
    - name: Notify Maintainece
      run: ./scripts/maintenance.sh
    
    - name: Notify
      run: ./scripts/notify.sh
