name: Scheduled Maintenance

on:
  schedule:
    - cron: '4 23 * * *' # Runs at 11:04 PM every day
    # - cron: '0 2 * * *' # Runs at 2 AM every day

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run backup script
      run: |
        chmod +x ./scripts/backup.sh
        ./scripts/backup.sh
    
    - name: Notify Maintainece
      run: |
        chmod +x ./scripts/maintenance.sh
        ./scripts/maintenance.sh
    
    - name: Notify
      run: |
        chmod +x ./scripts/notify.sh
        ./scripts/notify.sh
